### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sakyb7** [osmedeus/osmedeus-base#1]
why i am getting this error..?

![osmedeus](https://user-images.githubusercontent.com/42310984/147915390-02874bec-0b96-4ad5-b99a-927d54be35ad.png)

**Comment by j3ssie** [comment]
You need to `sudo su` first before running this command since the setup is done on `root` user.

**Comment by j3ssie** [comment]
Put the anwser here since I got asked by some other people too: https://docs.osmedeus.org/issue/
