### ISSUE TITLE
Add more modules

### ISSUE THREAD

**Issue by jakre1234** [osmedeus/osmedeus-base#5]
Add some good and more modules and workflows, or else create a community like nuclei templates. Directory module doen's seem to work always empty files

**Comment by j3ssie** [comment]
It's simply that there's no dirbscan. It very much depends on your target and wordlists.
You can check some similar questions here: https://docs.osmedeus.org/faq/
You can see how to customize the workflow here: https://docs.osmedeus.org/workflow/customize-your-own-workflow/

**Comment by j3ssie** [comment]
It's simply that there's no dirbscan. It very much depends on your target and wordlists.
You can check some similar questions here: https://docs.osmedeus.org/faq/
You can see how to customize the workflow here: https://docs.osmedeus.org/workflow/customize-your-own-workflow/
